repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        types: [python]
        exclude: ^tests/

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.9.0
  #   hooks:
  #     - id: mypy
  #       types: [python]
  #       additional_dependencies: [  dataclasses-json>=0.6.4, websocket-client>=1.2.1]
  #       exclude: '^tests/'

  - repo: https://github.com/ambv/black
    rev: 24.4.0
    hooks:
      - id: black
        args: [--check]
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--check,--profile=black]
