name: PR Checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  changelog:
    name: CHANGELOG
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check that CHANGELOG has been updated
      run: |
        # If this step fails, this means you haven't updated the CHANGELOG.md
        # file with notes on your contribution.
        git diff --name-only $(git merge-base origin/main HEAD) | grep '^CHANGELOG.md$' && echo "Thanks for helping keep our CHANGELOG up-to-date!"
   
  tests:
    name: Run Pytest
    runs-on: ubuntu-latest
    environment: OSSBUILD
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Set up Python and virtual environment
        uses: ./.github/actions/setup-venv
        with:
          python-version: "3.11"
          cache-prefix: "v1"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest tests/
        env:
          VITE_SERVER: ${{ secrets.VITE_SERVER }}
          VITE_DB_USER: ${{ secrets.VITE_DB_USER }}
          VITE_DB_PASS: ${{ secrets.VITE_DB_PASS }}
